### ISSUE TITLE
Compiling error on 2.4.0

### ISSUE THREAD

**Issue by g-balas** [Ali-Azmoud/flutter_xlider#10]
After updating to 2.4.0, I got this message when trying to run on Android device :

Compiler message:
...workspace_flutter/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_xlider-2.4.0/lib/flutter_xlider.dart:468:42: Error: Getter not found: 'visible'.
                  overflow: TextOverflow.visible,

**Comment by Ali-Azmoud** [comment]
Yeah I'm working on it, I don't know why bugs show themselves after I publish the package :(

**Comment by Ali-Azmoud** [comment]
Hi, its updated. hope this time no bug shows up.

**Comment by Ali-Azmoud** [comment]
This issue is fixed so I close it.
