### ISSUE TITLE
Override Tooltip

### ISSUE THREAD

**Issue by gmaxferr** [Ali-Azmoud/flutter_xlider#11]
Hello,
I've been using your range slider for a while and i've tried to customize it, but i'm getting stuck at the tooltip customization.
The thing is, is is possible to override it's display and put instead a CostumPainter object? I wanted to be able to fully paint a non-box object in the tooltip position...

Also, is it possible to implement an easy way to edit the decoration of the unselected track bar? I wanted to round the corners, but it's impossible without editing yout plugin's source code...

So, is it possible to do so?
Thanks, and great job with the plugin ;)

**Comment by Ali-Azmoud** [comment]
Hi. Sorry for the delayed reply and thank you for usage and feedback

> The thing is, is is possible to override it's display and put instead a CostumPainter object? I wanted to be able to fully paint a non-box object in the tooltip position...
It's not possible now, I don't know if I have enough time to add that feature but any contribution is welcomed

> Also, is it possible to implement an easy way to edit the decoration of the unselected track bar?
I would be great if you provide an image of what you want to do or what you've done so I understand better

**Comment by gmaxferr** [comment]
> 
> > 
>     Also, is it possible to implement an easy way to edit the decoration of the unselected track bar?
> 
> I would be great if you provide an image of what you want to do or what you've done so I understand better

I just wanted to add a border style to the track bar like rounding the corners

**Comment by Ali-Azmoud** [comment]
I'm so sorry for my delayed replies. I am very busy these days.
But I will update the package during next 3 or 4 days for sure.

**Comment by Ali-Azmoud** [comment]
Hi, after a long time, new version is out.
you can now customize trackbars easily.
tooltip custom paint isn't developed yet. sorry for this
