### ISSUE TITLE
FlutterSliderHatchMark keeps moving 

### ISSUE THREAD

**Issue by joaowd** [Ali-Azmoud/flutter_xlider#15]
Every time the FlutterSliderHatchMark disappears from the view (by scrolling), the next time it appears is 10/15px below from where it was previously.

[Video of the behaviour](https://www.youtube.com/watch?v=6Ip-MUNHzCg)

[Code](https://gist.github.com/joaowd/b4a724d16009169b62e744fe43b335d6)

**Comment by Ali-Azmoud** [comment]
Hi
I will test that and let you know, weird. Sorry for the late reply

**Comment by joaowd** [comment]
> Hi
> I will test that and let you know, weird. Sorry for the late reply

Did you produce the same error ?

**Comment by joaowd** [comment]
Found another bug when the FlutterSliderHatchMark, it doesn't update his size when you change the device rotation vertical/horizontal.

**Comment by joaowd** [comment]
I fixed the first problem adding a scaffold to the view. The second one keeps happening.

**Comment by Ali-Azmoud** [comment]
Hi
Both bugs are fixed in next version. I'm going to upload it within a couple of hours.

**Comment by joaowd** [comment]
@Ali-Azmoud thank you, you built a great widget!

**Comment by Ali-Azmoud** [comment]
Hi, new version is out. you can update now. sorry again for the late update.
