### ISSUE TITLE
Exception will occur with minimumDistance and double-precision floating-point errors.

### ISSUE THREAD

**Issue by tejashah88** [Ali-Azmoud/flutter_xlider#16]
If the difference between the lower and upper value is a little bit off due to double-precision floating-point errors, (ex. 0.6 - 0.5 == 0.09999999999999998), and the `minimumDistance` is slightly bigger (ex. 0.1), then an exception will be thrown. There needs to be an edge case handler for this, like an maximum epsilon value to account for the error.

**Comment by Ali-Azmoud** [comment]
Hi, can you share your code, so I can reproduce it. it would be easier to understand the problem. thanks.

**Comment by tejashah88** [comment]
@Ali-Azmoud Sorry for not getting back to you. I noticed the issue was closed, so has it been patched recently?

**Comment by Ali-Azmoud** [comment]
No, it's been a long time, yet you didn't provide more detail of your problem. I closed it until you share more details. feel free to open it

**Comment by tejashah88** [comment]
@Ali-Azmoud I can't seem to reproduce the bug. The exception might have been due to something else in my app. Thanks!
