### ISSUE TITLE
Please add tap to to increment/decrease by 1

### ISSUE THREAD

**Issue by tedchuang** [Ali-Azmoud/flutter_xlider#18]
This way, we can use it as a tally counter, such as counting foot traffic coming into the workshop presentation event. Thank you!

**Comment by Ali-Azmoud** [comment]
Hi, Could you please provide more details.

**Comment by tedchuang** [comment]
Good evening, Thank you for responding to this feature request.

This feature also help make fine adjustments to the slider count; if the max value is > 100, it's hard to slide to the precise number.

I was hoping to add a "minus" icon on the left side of the single slider, and a "plus" icon on the right side of the slider. Each tap of the "plus" icon would increase the count by one, with a little vibration haptic feedback as well. I can't find in the API where to alter the slider value externally.

Do you think it's possible to add the "minus" and "plus" icons on either side please?

**Comment by Ali-Azmoud** [comment]
if you want to increase or decrease the value of each slider handler simply change it's value!

```dart
double _sliderValue = 100;

...

FlutterSlider(
  ...
  values: [ _sliderValue ],
  ...
)

...

FlatButton(
    onPressed: () {
      _sliderValue -= 10000;
      setState(() {});
    },
    child: Text('-')),
FlatButton(
    onPressed: () {
      _sliderValue += 10000;
      setState(() {});
    },
    child: Text('+'))

```

**Comment by tedchuang** [comment]
Awesome! Thank you so very much sir :)
