### ISSUE TITLE
Slider Tap to select value doesn't trigger onDragCompleted event

### ISSUE THREAD

**Issue by adentutton** [Ali-Azmoud/flutter_xlider#21]
Currently, only the onDragging event is triggered when tapping the slider to select the value, is it possible to add the tap to trigger the onDragCompleted event? I am using the call back to update a list count after an API call and don't want to add the onDragging event to constantly keep calling the API?
Love the package so far!

**Comment by Ali-Azmoud** [comment]
Hi
Yeah, your requested feature will be added in the next version. stay tuned

**Comment by b-cancel** [comment]
@Ali-Azmoud I also REALLY need to be able to start a drag on tap

could you please implement this? or could you give me an idea about how you would do it so I can

Please and thank you!

**Comment by Ali-Azmoud** [comment]
> I also REALLY need to be able to start a drag on tap
Hi
Can you describe it a little bit more. I couldn't understand what exactly you want

**Comment by b-cancel** [comment]
@Ali-Azmoud basically think of something that looks like a slider but works like a scroll bar
right now on tap its possible to set the slider value
but the slider won't keep moving
I need to be possible for it to keep moving after the thumb tack gets repositioned

**Comment by Ali-Azmoud** [comment]
@adentutton Hi, your requested feature is added.

@b-cancel Hi, sorry your request isn't possible. because when you tap on slider, you touch somewhere outside of the Listener of the handler widget. It can't recognize your interaction to start drag.
