### ISSUE TITLE
[Question] - How to reduce slider padding

### ISSUE THREAD

**Issue by angel1st** [Ali-Azmoud/flutter_xlider#22]
Hi there,
First of all - thanks for the excellent package you have developed!
I have a question though - I am using the slider vertically, and since the screen width is limited, I would like to reduce the slide horizontal padding - is it possible to achieve this?

**Comment by Ali-Azmoud** [comment]
Hi, thanks for your feedback. 
wrap your slider with a parent widget, a `Container` for example, and give it a fixed width.

**Comment by aswinmohanme** [comment]
I can't remove the padding, can you give an example. It seems there is only left and top padding.

**Comment by aswinmohanme** [comment]
Also how to change the color of the slider ?

**Comment by Ali-Azmoud** [comment]
@aswinmohanme Everything about customization is documented, please read the docs.

About padding:
```
Container(
    width: 100,
    child: FlutterSlider( ... )
)
```

**Comment by johnmastri** [comment]
I am running into the same issue here. There is top and left padding by default with the slider. Wrapping in a container doesn't seem to help.


![image](https://user-images.githubusercontent.com/1303044/64930849-95185200-d7f1-11e9-9622-b244e94439e4.png)

**Comment by MrLepage** [comment]
Same problem
