### ISSUE TITLE
How to handle orientation change

### ISSUE THREAD

**Issue by mfarizon** [Ali-Azmoud/flutter_xlider#23]
Hey, 
it seems that the way that the slider reacts on orientation change can be improved. Right now, when changing from portrait to landscape, the active trackbar remains the same size while the full trackbar adapt itself to the new size of the screen.

![xlider-portait-to-landscape](https://user-images.githubusercontent.com/22452175/62479132-06092a80-b7ad-11e9-93b5-fb7c4db9f8a2.png)

When turning from landscape to portait, the active trackbar remains the same size as well, causing the active trackbar to be out of the screen (however, a tap on the active bar fixes the problem).

![xlider-landscape-to-portrait](https://user-images.githubusercontent.com/22452175/62479168-1ae5be00-b7ad-11e9-9fc8-d667ef0c615e.png)

**Comment by Ali-Azmoud** [comment]
Hi
Do you use the latest version ?

**Comment by mfarizon** [comment]
Yes, I use :
Flutter 1.7.8+hotfix.4, channel stable
Dart 2.4.0
and flutter_xlider 2.5.1

I can reproduce on both Android and iOS with the following minimal app : 
```
import 'package:flutter/material.dart';
import 'package:flutter_xlider/flutter_xlider.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  double _lowerValue;
  double _upperValue;

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    _lowerValue = 0;
    _upperValue = 200;
  }


  @override
  Widget build(BuildContext context) {

    return Scaffold(
      body: Center(
        child : FlutterSlider(
          min: 0,
          max: 200,
          values: [
            _lowerValue,
            _upperValue
          ],
          rangeSlider: true,
        ),
      ),
    );
  }
}
```

**Comment by Ali-Azmoud** [comment]
Okay, Thanks for your report. I will fix it tonight.

**Comment by Ali-Azmoud** [comment]
Hi, you can now update to the latest version. the bug is fixed.
