### ISSUE TITLE
Issues with rangeSlider

### ISSUE THREAD

**Issue by g-balas** [Ali-Azmoud/flutter_xlider#24]
We encountered two issues with ranged Slider : 

1 - The handles seems not horizontally aligned (see below, I added a red line, the right one seems 1 point below the left one)
I can reproduce this with default handlers, and also with custom ones.
![Screenshot_20190813-143756](https://user-images.githubusercontent.com/3330823/62943041-d88a3580-bdd9-11e9-94a0-3130c79a9d5c.jpg)
![Screenshot 2019-08-13 at 14 49 18](https://user-images.githubusercontent.com/3330823/62943049-dde78000-bdd9-11e9-8305-c7241e86f056.png)

`          Row(
              children: <Widget>[
                Expanded(
                  child: FlutterSlider(
                    values: [0, 10],
                    rangeSlider: true,
                    min: 0,
                    max: 100,
                  ),
                )
              ]
          ),
`

2 - When scrolling quickly one handle directly beyond the other one, sometimes it does not go to its maximum possible value.

**Comment by Ali-Azmoud** [comment]
Hi, sorry for my late response. I am traveling and don't have access to my laptop.
I will fix this issue asap. thanks for your report.

**Comment by seeyou888999** [comment]
Hello, if I want to change the icon of the slider or how the widget changes, do I support changing the icon or passing widget changes?

**Comment by Ali-Azmoud** [comment]
Hi @g-balas . sorry for my late response and action. Both of those bug you mentioned above are not fixed in latest version. I am going to close this issue, feel free to open it if you think the problem still exists
