### ISSUE TITLE
Tooltip doesn't show values from 0 to 1 

### ISSUE THREAD

**Issue by johnmastri** [Ali-Azmoud/flutter_xlider#28]
With the following settings the tool tip doesn't change from 0.0 until it reaches one.
```
returnWidget = new FlutterSlider(
              values: [.5],
              min: 0,
              max: 1.0,
              handler: new FlutterSliderHandler(
                child: _determineIcon(index)
              ),
              onDragCompleted: (handlerIndex, lowerValue, upperValue) {

**Comment by Ali-Azmoud** [comment]
Hi
sorry for my late response, I don't know if this is all your settings, but you are firing `onDragCompleted` so it will only update values when drag is completed.
I checked your code and it works well.

**Comment by Ali-Azmoud** [comment]
as @raacker mentioned, this happens because of slider default step which is 1. you need to set it manually to 0.1
I'm going to close this issue. feel free to reopen it if you need any help
