### ISSUE TITLE
How to remove chevron icons?

### ISSUE THREAD

**Issue by markzero** [Ali-Azmoud/flutter_xlider#3]
Hi, nice plugin!
It's very easy to use, but how can we remove chevron (chevron_left and chevron_right) default icons on handlers without making new handler? Is there an easy way?

**Comment by Ali-Azmoud** [comment]
Hi
In current version, sorry there isn't a way to modify handlers but it's a good idea to have it for the next version. for now, you need to remake it.

**Comment by Ali-Azmoud** [comment]
Hi. new version is available, you can now use `icon` property to only modify handler, if you want to completely remake it, you need to use `child`

**Comment by markzero** [comment]
Works great, thanks for the update!
