### ISSUE TITLE
can not change FlutterSlider width

### ISSUE THREAD

**Issue by Ahmedtaha123** [Ali-Azmoud/flutter_xlider#33]
if i wrap FlutterSlider with Container and give Container width FlutterSlider  not change 
any help

**Comment by Ali-Azmoud** [comment]
Hi
Can you share your code so that I can reproduce it? thanks

**Comment by Ali-Azmoud** [comment]
Since you haven't answered this reply for a long time, I'm going to close this issue. Feel free to reopen it if you need to

**Comment by lvlasuod** [comment]
Hey thanks for your useful plugin, but I have the same problem with this plugin I want to increase the width of the trackbar, how can I approach?
