### ISSUE TITLE
when add attribute axis: Axis.vertical ，throw error

### ISSUE THREAD

**Issue by jtans** [Ali-Azmoud/flutter_xlider#37]
when i write the code like :
`FlutterSlider(
          values: [10],
          axis: Axis.vertical,
          max: 100,
          min: 0,
          trackBar: FlutterSliderTrackBar(
            inactiveTrackBar: BoxDecoration(
              borderRadius: BorderRadius.circular(20),
              color: Colors.black12,
              border: Border.all(width: 3, color: Colors.blue),
            ),
            activeTrackBar: BoxDecoration(
                borderRadius: BorderRadius.circular(4),
                color: Colors.blue.withOpacity(0.5)),
          ),
        )`

> throw error

                              

[38;5;248m════════ Exception caught by rendering library ═════════════════════════════════[39;49m
[38;5;244mThe following assertion was thrown during performLayout():[39;49m
BoxConstraints forces an infinite height.

[38;5;244mThese invalid constraints were provided to RenderPadding's layout() function by the following function, which probably computed the invalid constraints in question:
  RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:259:13)
[39;49m[38;5;244mThe offending constraints were: BoxConstraints(w=63.0, h=Infinity)[39;49m
[38;5;244mUser-created ancestor of the error-causing widget was[39;49m
    [38;5;248mFlutterSlider[39;49m
[38;5;244mWhen the exception was thrown, this was the stack[39;49m
[38;5;244m#0      BoxConstraints.debugAssertIsValid.<anonymous closure>.throwError[39;49m
[38;5;244m#1      BoxConstraints.debugAssertIsValid.<anonymous closure>[39;49m
[38;5;244m#2      BoxConstraints.debugAssertIsValid[39;49m
[38;5;244m#3      RenderObject.layout[39;49m
[38;5;244m#4      RenderConstrainedBox.performLayout[39;49m
[38;5;244m...[39;49m
[38;5;244mThe following RenderObject was being processed when the exception was fired: RenderConstrainedBox#3b389 relayoutBoundary=up4 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE[39;49m
[38;5;244mRenderObject: RenderConstrainedBox#3b389 relayoutBoundary=up4 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE[39;49m
    [38;5;244mparentData: offset=Offset(0.0, 0.0) (can use size)[39;49m
    [38;5;244mconstraints: BoxConstraints(0.0<=w<=414.0, 0.0<=h<=Infinity)[39;49m
    [38;5;244msize: Size(414.0, 63.0)[39;49m
    [38;5;244madditionalConstraints: BoxConstraints(w=63.0, h=Infinity)[39;49m
    [38;5;244mchild: RenderPadding#f850f NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE[39;49m
        [38;5;244mparentData: <none> (can use size)[39;49m
        [38;5;244mconstraints: BoxConstraints(w=414.0, h=63.0)[39;49m
        [38;5;244msize: Size(414.0, 63.0)[39;49m
        [38;5;244mpadding: EdgeInsets(17.5, 17.5, 0.0, 0.0)[39;49m
        [38;5;244mtextDirection: ltr[39;49m
        [38;5;244mchild: RenderStack#7afda NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE[39;49m
            [38;5;244mparentData: offset=Offset(17.5, 17.5) (can use size)[39;49m
            [38;5;244mconstraints: BoxConstraints(w=396.5, h=45.5)[39;49m
            [38;5;244msize: Size(396.5, 45.5)[39;49m
            [38;5;244malignment: AlignmentDirectional.topStart[39;49m
            [38;5;244mtextDirection: ltr[39;49m
            [38;5;244mfit: loose[39;49m
            [38;5;244moverflow: visible[39;49m
            [38;5;244mchild 1: RenderPositionedBox#c3107 relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE[39;49m
                [38;5;244mparentData: top=17.5; right=0.0; left=0.0; offset=Offset(0.0, 17.5) (can use size)[39;49m
                [38;5;244mconstraints: BoxConstraints(w=396.5, 0.0<=h<=Infinity)[39;49m
                [38;5;244msize: Size(396.5, 3.0)[39;49m
                [38;5;244malignment: center[39;49m
                [38;5;244mtextDirection: ltr[39;49m
                [38;5;244mwidthFactor: expand[39;49m
                [38;5;244mheightFactor: expand[39;49m
                [38;5;244mchild: RenderConstrainedBox#9820f relayoutBoundary=up2 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE[39;49m
                    [38;5;244mparentData: offset=Offset(26.3, 0.0) (can use size)[39;49m
                    [38;5;244mconstraints: BoxConstraints(0.0<=w<=396.5, 0.0<=h<=Infinity)[39;49m
                    [38;5;244msize: Size(344.0, 3.0)[39;49m
                    [38;5;244madditionalConstraints: BoxConstraints(w=3.0, h=Infinity)[39;49m
            [38;5;244mchild 2: RenderPositionedBox#f3ee4 relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE[39;49m
                [38;5;244mparentData: top=31.5; right=0.0; left=0.0; offset=Offset(0.0, 31.5) (can use size)[39;49m
                [38;5;244mconstraints: BoxConstraints(w=396.5, 0.0<=h<=Infinity)[39;49m
                [38;5;244msize: Size(396.5, 1.0)[39;49m
                [38;5;244malignment: center[39;49m
                [38;5;244mtextDirection: ltr[39;49m
                [38;5;244mwidthFactor: expand[39;49m
                [38;5;244mheightFactor: expand[39;49m
                [38;5;244mchild: RenderConstrainedBox#89c2d relayoutBoundary=up2 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE[39;49m
                    [38;5;244mparentData: offset=Offset(196.5, 0.0) (can use size)[39;49m
                    [38;5;244mconstraints: BoxConstraints(0.0<=w<=396.5, 0.0<=h<=Infinity)[39;49m
                    [38;5;244msize: Size(3.5, 1.0)[39;49m
                    [38;5;244madditionalConstraints: BoxConstraints(w=3.5, h=1.0)[39;49m
            [38;5;244mchild 3: RenderOpacity#3bd0f NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE[39;49m
                [38;5;244mparentData: top=0.0; right=0.0; bottom=0.0; left=0.0; offset=Offset(0.0, 0.0) (can use size)[39;49m
                [38;5;244mconstraints: BoxConstraints(w=396.5, h=45.5)[39;49m
                [38;5;244msize: Size(396.5, 45.5)[39;49m
                [38;5;244mopacity: 0.0[39;49m
                [38;5;244mchild: RenderPointerListener#c2553 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE[39;49m
                    [38;5;244mparentData: <none> (can use size)[39;49m
                    [38;5;244mconstraints: BoxConstraints(w=396.5, h=45.5)[39;49m
                    [38;5;244msize: Size(396.5, 45.5)[39;49m
                    [38;5;244mbehavior: deferToChild[39;49m
                    [38;5;244mlisteners: down[39;49m
            [38;5;244mchild 4: RenderLimitedBox#473e7 relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE[39;49m
                [38;5;244mparentData: not positioned; offset=Offset(0.0, 0.0) (can use size)[39;49m
                [38;5;244mconstraints: BoxConstraints(0.0<=w<=396.5, 0.0<=h<=45.5)[39;49m
                [38;5;244msize: Size(396.5, 45.5)[39;49m
                [38;5;244mmaxWidth: 0.0[39;49m
                [38;5;244mmaxHeight: 0.0[39;49m
                [38;5;244mchild: RenderConstrainedBox#09de0 relayoutBoundary=up2 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE[39;49m
                    [38;5;244mparentData: <none> (can use size)[39;49m
                    [38;5;244mconstraints: BoxConstraints(0.0<=w<=396.5, 0.0<=h<=45.5)[39;49m
                    [38;5;244msize: Size(396.5, 45.5)[39;49m
                    [38;5;244madditionalConstraints: BoxConstraints(biggest)[39;49m
            [38;5;244mchild 5: RenderPointerListener#f31f4 relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE[39;49m
                [38;5;244mparentData: top=0.0; right=0.0; left=278.4; offset=Offset(278.4, 0.0) (can use size)[39;49m
                [38;5;244mconstraints: BoxConstraints(w=118.1, 0.0<=h<=Infinity)[39;49m
                [38;5;244msize: Size(118.1, 65.0)[39;49m
                [38;5;244mbehavior: deferToChild[39;49m
                [38;5;244mlisteners: down, move, up[39;49m
                [38;5;244mchild: RenderPointerListener#faa4b relayoutBoundary=up2 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE[39;49m
                    [38;5;244mparentData: <none> (can use size)[39;49m
                    [38;5;244mconstraints: BoxConstraints(w=118.1, 0.0<=h<=Infinity)[39;49m
                    [38;5;244msize: Size(118.1, 65.0)[39;49m
                    [38;5;244mbehavior: deferToChild[39;49m
                    [38;5;244mlisteners: down[39;49m
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m

[38;5;248m════════ Exception caught by rendering library ═════════════════════════════════[39;49m
BoxConstraints forces an infinite height.
[38;5;244mUser-created ancestor of the error-causing widget was[39;49m
    [38;5;248mFlutterSlider[39;49m
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m
Reloaded 4 of 612 libraries in 427ms.

**Comment by Ali-Azmoud** [comment]
Hi
You need to wrap your slider inside another widget, for example, a `Container` with a given height.
