### ISSUE TITLE
How to stretch slider to fit container?

### ISSUE THREAD

**Issue by samir97** [Ali-Azmoud/flutter_xlider#4]
Hi, amazing work!

How do I removing the padding so that the slider stretches to fit the whole container in vertical orientation?

Thanks
<img width="297" alt="Screenshot 2019-03-10 at 23 10 57" src="https://user-images.githubusercontent.com/29393146/54092961-42656580-438a-11e9-9145-665ff036662b.png">

**Comment by Ali-Azmoud** [comment]
Hi, thank you

Sorry, I couldn't understand but I think this can help you. the slider itself has no padding. there is a little issue about trackbar's height and width in single mode, which it will be solved in the next version

```dart
        Container(
              color: Colors.black.withOpacity(0.05),
              height: 300,
              padding: EdgeInsets.only(left: 100),
              alignment: Alignment.centerLeft,
              child: FlutterSlider(
                  axis: Axis.vertical,
                  ...
              )
          )

```
or if you don't want to set the height or width manually , use `expanded` or `flexible` inside a column or row.

if this is not what you asked, please provide some more details.

**Comment by samir97** [comment]
> Hi, thank you
> 
> Sorry, I couldn't understand but I think this can help you. the slider itself has no padding. there is a little issue about trackbar's height and width in single mode, which it will be solved in the next version
> 
> ```dart
>         Container(
>               color: Colors.black.withOpacity(0.05),
>               height: 300,
>               padding: EdgeInsets.only(left: 100),
>               alignment: Alignment.centerLeft,
>               child: FlutterSlider(
>                   axis: Axis.vertical,
>                   ...
>               )
>           )
> ```
> 
> or if you don't want to set the height or width manually , use `expanded` or `flexible` inside a column or row.
> 
> if this is not what you asked, please provide some more details.

Thanks for the quick reply, this helped a lot. It turns out the reason for the padding was because the widget was inside a `SafeArea` which I assumed would only apply padding if the widget went under the notch.

**Comment by devnta** [comment]
@Ali-Azmoud How to stretch slider to fit red background?
![image](https://github.com/Ali-Azmoud/flutter_xlider/assets/102949116/14b6a6e1-634c-4e19-9af9-57773cfa6555)
