### ISSUE TITLE
selectByTap not working properly 

### ISSUE THREAD

**Issue by JobinCheriyanExperion** [Ali-Azmoud/flutter_xlider#40]
when tap on the slider, value not updating on first tap and some times showing wrong values which is not appropriate for the current slider tracker position.

**Comment by Ali-Azmoud** [comment]
Hi. please provide more details. `min`, `max`, `jump`, `direction`, `step`. thanks.

**Comment by JobinCheriyanExperion** [comment]
FlutterSlider(
                                    tooltip: FlutterSliderTooltip(
                                      disabled: true,
                                    ),
                                    handlerHeight: 23,
                                    handlerWidth: 23,
                                    handler: FlutterSliderHandler(
                                      decoration: BoxDecoration(),
                                      child: Container(
                                        child: Container(
                                          margin: EdgeInsets.all(5),
                                          decoration: BoxDecoration(
                                              color: Color(0x300a567a),
                                              shape: BoxShape.circle),
                                        ),
                                        decoration: BoxDecoration(
                                          color: Colors.white,
                                          shape: BoxShape.circle,
                                          boxShadow: [
                                            BoxShadow(
                                                color: Colors.blue
                                                    .withOpacity(0.3),
                                                spreadRadius: 0.05,
                                                blurRadius: 5,
                                                offset: Offset(0, 1))
                                          ],
                                        ),
                                      ),
                                    ),
                                    trackBar: FlutterSliderTrackBar(
                                      inactiveTrackBar: BoxDecoration(
                                        color: Color(0xff38b7c9),
                                        borderRadius: BorderRadius.all(
                                            Radius.circular(4)),
                                      ),
                                      activeTrackBar: BoxDecoration(
                                        color: Color(0xff38b7c9),
                                        borderRadius: BorderRadius.all(
                                            Radius.circular(4)),
                                      ),
                                      activeTrackBarHeight: 8,
                                      inactiveTrackBarHeight: 8,
                                    ),
                                    values: [10],
                                    max: 124,
                                    min: 0,
                                    selectByTap: true,
                                    onDragging:
                                        (handlerIndex, lowerValue, upperValue) {
                                      setState(() {
                                        inputAmoutController.text =
                                            _lowerValue.toStringAsFixed(2);
                                        _lowerValue = lowerValue;
                                      });
                                    },

                                    onDragCompleted:
                                        (handlerIndex, lowerValue, upperValue) {
                                      setState(() {
                                        inputAmoutController.text =
                                            _lowerValue.toStringAsFixed(2);
                                        _lowerValue = lowerValue;

                                      });
                                    })

**Comment by Ali-Azmoud** [comment]
It's working fine for me. I commented out the lines you update `inputAmoutController`.
Maybe you need to update `inputAmoutController` after `_lowerValue = lowerValue`.  cuz from what I see in your code, you're first setting the old value of `_lowerValue` to `inputAmoutController` then updating `_lowerValue` which seems a bit weird unless it's intended to work like that

**Comment by JobinCheriyanExperion** [comment]
Thank you @Ali-Azmoud  .... Thank you for your valuable time
