### ISSUE TITLE
What happend to numberFormat in "FlutterSliderTooltip" constructor?

### ISSUE THREAD

**Issue by marco2250** [Ali-Azmoud/flutter_xlider#41]
It seems parameter got removed...

**Comment by Ali-Azmoud** [comment]
Hi
Yeah, it's removed because of #29 and #27 and similar issues in the future.
You can use `custom` callback in `FlutterSliderTooltip` and use `intl` and return your own value and widget. Also, you need to import `intl` manually in your project
