### ISSUE TITLE
How to set the value of the slider

### ISSUE THREAD

**Issue by junghyun397** [Ali-Azmoud/flutter_xlider#43]
Hello, is there a way to externally specify the slider's current position? Maybe... in the following way,
```dart
GlobalKey<FlutterSliderState> _sliderKey = GlobalKey<FlutterSliderState>();
_sliderKey.currentState.setSliderValue(100);
```
When A and B sliders needed to move together, I couldn't find a way to implement them without modifying flutter_xlider's code (when B sliders had to be synchronized to A and vice versa).

**Comment by Ali-Azmoud** [comment]
```
double _lowerValue = 0;

...

FlutterSlider(
              values: [_lowerValue],
              min: 0,
              max: 100,
              step: 1,
              onDragging: (lowerValue, upperValue, index){
                _lowerValue = upperValue.toDouble();
                print(upperValue);
                setState(() {

                });
              },
            ),
            FlutterSlider(
              values: [_lowerValue],
              min: 0,
              max: 100,
              step: 1,
              onDragging: (lowerValue, upperValue, index){
                _lowerValue = upperValue.toDouble();
                print(upperValue);
                setState(() {

                });
              },
            ),
```

Do you want something like above ? if this is not what you want, please describe it a little more.  
There is a bug in this version which `lowerValue` and `upperValue` are swaped !

**Comment by junghyun397** [comment]
Thank you. The desired function works in the correct way. Cool package is always a favorite. :)

**Comment by Ali-Azmoud** [comment]
@junghyun397 please see the updated answer. the order of parameters in `onDragging` method was incorrect which it is now corrected.
