### ISSUE TITLE
called on null

### ISSUE THREAD

**Issue by parisa3084** [Ali-Azmoud/flutter_xlider#45]
hi! when I run your code in example file it has this error : the getter 'boxstyle' was called on null.whats the problem??

**Comment by Ali-Azmoud** [comment]
کدوم مثال رو اجرا کردید. کدش رو قرار بدید اینجا تا اصلاح کنم. متاسفانه مثال ها یکم قدیمی هستن و با آخرین نسخه همخوانی ندارند

**Comment by Ali-Azmoud** [comment]
لطفا این ویژگی رو 
`tooltip: FlutterSliderTooltip()`
رو به تنظیمات اسلایدرتون اضافه کنید تا امشب که من این باگ رو رفع کنم

**Comment by parisa3084** [comment]
سلام خیلی ممنون مشکلم حل شد دقیقا مشکل همین tooltip بود
