### ISSUE TITLE
`NoSuchMethodError`: The getter 'boxStyle' was called on null.

### ISSUE THREAD

**Issue by hinterlandsupplyco** [Ali-Azmoud/flutter_xlider#46]
Even the most basic  default code does not work and throws an the error in the title.

```dart
FlutterSlider(
  rangeSlider: true,
  min: 0,
  max: 100,
  values: [10, 50],
  onDragCompleted: (a,b,c) {});
```

**Comment by Ali-Azmoud** [comment]
Hi. please add this property `tooltip: FlutterSliderTooltip(),` to your slider for now. I fix this bug tonight

**Comment by hinterlandsupplyco** [comment]
> Hi. please add this property `tooltip: FlutterSliderTooltip(),` to your slider for now. I fix this bug tonight

This fixes it. Thank you! 

I'll leave the bug open for you to close.
