### ISSUE TITLE
How do I fix the minimum value in the bar?

### ISSUE THREAD

**Issue by MostafaDadkhah** [Ali-Azmoud/flutter_xlider#48]
I want a simple slider  to keep me fixed and just move my right handler. But when I create a sub interval of min and max I can move this interval over the whole interval and the min value changes in that case. I don't want this to happen and I just want my values to change between 1and 100, not between 5and 100, for example. This is my code : 
``` Center(child:  SizedBox(width: 400,
             child: FlutterSlider(
                 
                    selectByTap: false,
                    jump: false,
                    values: [50],
                    max: 100,
                    min: 1,
                    
                    onDragCompleted: (handlerIndex, lowerValue, upperValue) {
                    alpha = lowerValue/100;
                   
                    }
                  ),),)

**Comment by Ali-Azmoud** [comment]
درود. وقت بخیر. متوجه نشدم منظورتون چیه. لطفا بیشتر توضیح بدید. سپاس
