### ISSUE TITLE
[Question] How could I desable the tooltip animation or change its direction?

### ISSUE THREAD

**Issue by mrverdant13** [Ali-Azmoud/flutter_xlider#53]
I am using a vertical slider. The tooltip has a vertical animation.
I am looking for a method to use a horizontal animation or, if there is no way to do it, disable the whole animation.

**Comment by ferrets6** [comment]
Same question.
With vertical slider, tooltip should be set as "horizontal" or even disable the animation

**Comment by ferrets6** [comment]
Made a pull request to disable animation #57

**Comment by Ali-Azmoud** [comment]
Hi, disabling animation is already done. I'm working on the horizontal tooltip now.

**Comment by Ali-Azmoud** [comment]
you can now change the tooltip direction or disable it in the latest version. I close this issue if you think the problem still exists reopen it.
