### ISSUE TITLE
Is it possible to have value as tickmark with this plugin

### ISSUE THREAD

**Issue by RomanJos** [Ali-Azmoud/flutter_xlider#54]
Hi, I'm wondering if I could achieve something like this with this library :
![image](https://user-images.githubusercontent.com/42180076/79966973-8207e780-848e-11ea-876d-888e4697e5f2.png)

**Comment by Ali-Azmoud** [comment]
Hi
Not with the current version, but with the next version, you can

![](http://flutterdev.site/public/images/slider.gif)

The next version is out in about 1 or 2 days from now

**Comment by RomanJos** [comment]
Daaaamn man thank you so much !! I've been struggling for like 5 days !!

**Comment by Ali-Azmoud** [comment]
Hey.

**Comment by RomanJos** [comment]
Maaan thank you so much for your work

**Comment by Ali-Azmoud** [comment]
Your welcome, this is how I've implemented the labels. you can do it with your own logic. see the updated code.

**Comment by RomanJos** [comment]
I got somes issue making it work notably with `FlutterSliderHatchMarkLabel`, I needed to round the percent value in order to have them displayed but after that its just mostly small fixes that can be easily fixed like :

Is there a way to remove the extra padding ? 
![image](https://user-images.githubusercontent.com/42180076/80803900-e8d68080-8bb3-11ea-8099-6369d2be026d.png)
I rounded the end of the slider but now the hatch are off track, also the thumb are cut when they are dragged at the end : 
![image](https://user-images.githubusercontent.com/42180076/80804086-67332280-8bb4-11ea-9d64-2e5263a3facd.png) ![image](https://user-images.githubusercontent.com/42180076/80805176-a151f380-8bb7-11ea-8ea0-d707f4c977cc.png)
Is there any other way instead rebuilding the entire hatchMark to highlight the one selected ? Currently its a little buggy and sometimes I got this : 
![image](https://user-images.githubusercontent.com/42180076/80804322-14a63600-8bb5-11ea-85ee-7563ba5571ae.png)
This is not a graphics artifact but more like how you handled the control, if I put the two thumb at the same percentage moving the inactive track of the first thumb don't do anything where the second thub make it move :
![ezgif-3-afc134b0e9bc](https://user-images.githubusercontent.com/42180076/80804718-466bcc80-8bb6-11ea-9aac-149d0321fb07.gif)

Again thank you for this library !

**Comment by Ali-Azmoud** [comment]
Hi, w8 for the next patch release. today or tomorrow

**Comment by Ali-Azmoud** [comment]
`Is there a way to remove the extra padding ?` I think you mean `distanceFromTrackBar`. change it's number to get the result you want

`Is there any other way instead rebuilding the entire hatchMark to highlight the one selected`
No, flutter doesn't work like that, there is no `modify`. but the problem is solved in the latest version.

and about that control bug, it is fixed as well.

**Comment by RomanJos** [comment]
For removing the extra padding I modified 1.8 to 1 to only get the width of the track
https://github.com/Ali-Azmoud/flutter_xlider/blob/011b0e42fd81d5f2f964385fe68382d0bf11179c/lib/flutter_xlider.dart#L303
1.8 vs 1:
![image](https://user-images.githubusercontent.com/42180076/80857253-fe4db800-8c50-11ea-8aa9-ec2d7322df45.png) 
![image](https://user-images.githubusercontent.com/42180076/80857265-276e4880-8c51-11ea-81ad-a1c62e70a2c8.png)

To avoid rebuilding the entire hatchmark, you could use animation I believe ? Having two hatchmark, one active, one inactive and animating with SizeTransition could replace rebuilding everything
What did you do to fix this ?

Nice !
