### ISSUE TITLE
no response on selectByTap

### ISSUE THREAD

**Issue by ferrets6** [Ali-Azmoud/flutter_xlider#56]
Hi,
first of all, thanks for this usefull package! :)

However, I have a problem with selectByTap: it does not make anything.
I also tried to force selectByTap to true (it shouldn't be needed, as it's true by default), but again nothing appens.
No value changed nor handler moved.

Normal "drag and drog" on the handler works well.

What's wrong?
Thanks

```
import 'package:flutter/material.dart';
import 'package:flutter_xlider/flutter_xlider.dart';

class DirectionAdjustment2 extends StatefulWidget {
  final Function onAdjustmentDone;
  final double startValue;
  final double height;

  DirectionAdjustment2({this.startValue, this.onAdjustmentDone, this.height});

  @override
  _DirectionAdjustment2State createState() => _DirectionAdjustment2State();
}

class _DirectionAdjustment2State extends State<DirectionAdjustment2> {
  double _value = 100;

  @override
  Widget build(BuildContext context) {
    return Container(
      height: widget.height,
      child: FlutterSlider(
        rangeSlider: false,
        min: 0,
        max: 100,
        axis: Axis.vertical,
        rtl: true,
        values: [_value],
        selectByTap: true,
        handlerWidth: 20,
        trackBar: FlutterSliderTrackBar(
          inactiveTrackBarHeight: 2,
          activeTrackBarHeight: 2,
        ),
        handler: FlutterSliderHandler(
          child: Container(),
          decoration: BoxDecoration(
              color: Theme.of(context).accentColor, shape: BoxShape.circle),
        ),
        onDragStarted: (_, __, ___) {
          // TODO add haptic feedback
          Feedback.forTap(context);
        },
        onDragCompleted: (handlerIndex, newValue, _) {
          double valueNormalized =
              num.parse((newValue / 100).toStringAsFixed(2));
          widget.onAdjustmentDone(valueNormalized);
        },
      ),
    );
  }
}
```
Preview
![image](https://user-images.githubusercontent.com/17033305/80309708-0502a800-87d7-11ea-90ea-bfb018472ed8.png)

**Comment by ferrets6** [comment]
I have found a sort of "workaround", but I don't make a Pull Request because I don't know exactly what there is "under the hood".

However, adding this line, the selectByTap works (quite) well.
(but sometimes, nonsense, the event onDragCompleted seems to be not fired)

![image](https://user-images.githubusercontent.com/17033305/80321140-1372b300-881b-11ea-85dd-7d9df6490995.png)

**Comment by Ali-Azmoud** [comment]
Hi, it's a known bug and is fixed in the latest unreleased version. unfortunately, the `selectByTap` feature is completely disabled in non-range slider in the current version. the next version is out in 1 or 2 days from now

**Comment by ferrets6** [comment]
Good! Waiting for the release, thank you!

**Comment by Ali-Azmoud** [comment]
Hi, the new version is out. please check it out.
