### ISSUE TITLE
Error when in TabBar

### ISSUE THREAD

**Issue by xjerryg** [Ali-Azmoud/flutter_xlider#58]
When placed in TabBar I get the following error when swiping from the tab with FlutterSlider to another tab.

════════ Exception caught by scheduler library ═════════════════════════════════
The following assertion was thrown during a scheduler callback:
'package:flutter/src/widgets/media_query.dart': Failed assertion: line 791 pos 12: 'context != null': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack
#2      MediaQuery.of 
package:flutter/…/widgets/media_query.dart:791
#3      _FlutterSliderState._renderBoxInitialization  (package:flutter_xlider/flutter_xlider.dart:2025:21)
#4      _FlutterSliderState.initMethod.<anonymous closure>  (package:flutter_xlider/flutter_xlider.dart:407:7)
#5      SchedulerBinding._invokeFrameCallback 
package:flutter/…/scheduler/binding.dart:1102
#6      SchedulerBinding.handleDrawFrame 
package:flutter/…/scheduler/binding.dart:1049
...

**Comment by Ali-Azmoud** [comment]
I tested it out and got not `Exception`. Could you please share a simple version of your code so that I can reproduce it. Thanks

**Comment by xjerryg** [comment]
You are right, I'm sorry. When separated in small simple project I'm also not able to get that exception. It has to be somehow connected with something else in the project. 

The strange thing is that if I remove custom definition of tooltip it stops. I will keep trying to find it and let you know if it will be somehow connected with your code.
