### ISSUE TITLE
onDragStarted and onDragCompleted not fired on selectByTap and not rangeSlider

### ISSUE THREAD

**Issue by ferrets6** [Ali-Azmoud/flutter_xlider#60]
I tried the new version you've just released, and found that onDragStarted and onDragCompleted are not fired on selectByTap = true and rangeSlider = false, **if you tap and slide**.
In that case the only event fired is onDragging.

The single tap fires correctly onDragStarted  and onDragCompleted.

**Comment by Ali-Azmoud** [comment]
Hi, check out the new version. Thanks for your bug report
