### ISSUE TITLE
Default initial value for Slider

### ISSUE THREAD

**Issue by pisa97** [Ali-Azmoud/flutter_xlider#63]
Hi,

Thank you so much for this wonderful widget. Why is it not possible to add an initial value to the slider?

**Comment by Ali-Azmoud** [comment]
Hi, thanks
Sorry, I couldn't understand what you mean, can you provide more details

**Comment by pisa97** [comment]
> Hi, thanks
> Sorry, I couldn't understand what you mean, can you provide more details

I mean, set a default value to the slider, but looking at the closed issues I find the solution. I'm sorry for that. 

I suggest you to add this inside the examples because it is not so much clear how to do that.
Again, thank you!

**Comment by om-chevli** [comment]
> > Hi, thanks
> > Sorry, I couldn't understand what you mean, can you provide more details
> 
> I mean, set a default value to the slider, but looking at the closed issues I find the solution. I'm sorry for that.
> 
> I suggest you to add this inside the examples because it is not so much clear how to do that.
> Again, thank you!

Hey! What's the solution for this problem @pisa97 ?
