### ISSUE TITLE
Set state inside xlider  isn't happening when [values] are set to same value as xlider was created

### ISSUE THREAD

**Issue by AlexBacich** [Ali-Azmoud/flutter_xlider#64]
Thanks for awesome library. Great job. 

I want to report an issue. 

When xLider is created it is created with default value (50 in my case). When you use external buttons to setState with new value  - xLider isn't rebuilding when reaches 50.
Let's say you were on 50 and tap on + button. Value becomes 51 - xLider rebuilds - everything is fine. But if you tap on - then - value becomes 50 again (same as initial value). xLider isn't rebuilt. You can see dot stays on 51 value

Let me explain and show in video.
https://take.ms/k4dcX

Code snippet (I've removed everything unnecessary and still reproduced)

```
class FuturesLeverageBody extends StatefulWidget {
  @override
  _FuturesLeverageBodyState createState() => _FuturesLeverageBodyState();
}

class _FuturesLeverageBodyState extends State<FuturesLeverageBody> {
  double value = 50;

  @override
  Widget build(BuildContext context) {
    return Column(
      children: <Widget>[
        Row(
          children: <Widget>[
            FlatButton(
              child: Text('-'),
              onPressed: () {
                setState(() {
                  value--;
                });
              },
            ),
            Spacer(),
            FlatButton(
              child: Text('+'),
              onPressed: () {
                setState(() {
                  value++;
                });
              },
            ),
          ],
        ),
        FlutterSlider(
          values: [value],
          min: 0,
          max: 125,
          jump: true,
          selectByTap: true,
          step: 25,
        ),
      ],
    );
  }
}

```

p.s. you mentioned showcases are welcomed. You can see this showcase from my app. if you want I can extract whole code for showing as an example in you about pages. Again thanks for awesome widget.

**Comment by Ali-Azmoud** [comment]
Hi, thanks for your report. 
please try the latest version, I tested it and it works fine for me.
and for the showcase, yes absolutely. it will be awesome

**Comment by Ali-Azmoud** [comment]
Hi, thanks for your report. 
Yeah, that's a bug and this behavior is made to prevent some other bugs! I start working on this tonight. 
and for the showcase, yeah absolutely. it would be awesome

**Comment by AlexBacich** [comment]
Another issue I've noticed (maybe I should fill another bug) - if I put custom values - touch area is decreased significantly to tiny dots representing declared custom values. I guess expected behavior is to still be able to touch anywhere and slider value goes to closest custom value.

**Comment by Ali-Azmoud** [comment]
Hi, there is a `dev` version available, since there are some other updates, I will release a stable version when those are available as well. You can use this `dev` version until then. 
thanks

**Comment by Ali-Azmoud** [comment]
> Another issue I've noticed (maybe I should fill another bug) - if I put custom values - touch area is decreased significantly to tiny dots representing declared custom values. I guess expected behavior is to still be able to touch anywhere and slider value goes to closest custom value.
It would be better to show an image, it's still not clear to me :(

for the step-range, use `stepRange` and `FlutterSliderStepBehavior`. the names may change in the next version

**Comment by Ali-Azmoud** [comment]
Hi, next version is out. Its more customizable. Its good to see your slider in showcase section.

**Comment by AlexBacich** [comment]
Hi, thank you! Will take a look shortly and prepare stand-alone version for showcase. 
As well as will provide details on issue with custom values.
