### ISSUE TITLE
axis: Axis.vertical show up inverted: Maximum value at bottom

### ISSUE THREAD

**Issue by hugocharbonneau** [Ali-Azmoud/flutter_xlider#69]
I am using this constructor's param but the render shows inverted. Maximum value is down. And arrow point down.

FlutterSlider(
                    values: [50],
                    max: 100,
                    min: 0,
                    axis: Axis.vertical,
);

flutter_xlider 3.4.0
![Capture](https://user-images.githubusercontent.com/9326043/81957034-0f47e300-95da-11ea-80a4-923b4cfae4ee.PNG)

**Comment by Ali-Azmoud** [comment]
Hi
use `rtl: true`

**Comment by hugocharbonneau** [comment]
That was very easy! Thanks a lot.

Hugo
514-699-9695


Le jeu. 14 mai 2020, à 14 h 24, Ali-Azmoud <notifications@github.com> a
écrit :
