### ISSUE TITLE
On Tap on the slider to select value without dragging the thumb ?

### ISSUE THREAD

**Issue by g-balas** [Ali-Azmoud/flutter_xlider#7]
Hey, is it possible to select a value directly with a on Tap event on the slider itself ?

Thanks, and great job btw.

**Comment by Ali-Azmoud** [comment]
Hi
Yeah, actually this feature is available in the  next version. You can update tonight or tomorrow ( local time ).

**Comment by g-balas** [comment]
Love you guys.

**Comment by Ali-Azmoud** [comment]
Hi, you can update to the latest version.

**Comment by g-balas** [comment]
Seems perfect, thanks !
