### ISSUE TITLE
Slider is rebuilding when setState(){};

### ISSUE THREAD

**Issue by zpawlo02** [Ali-Azmoud/flutter_xlider#75]
When I'm trying to use setState in onDragCompleted() method, widget is rebuilding and slider is going back to starting position

**Comment by Ali-Azmoud** [comment]
Hi. you need a tiny change in your slider.
change `values: [ 0 ]` to `values: [ _lowerValue ]` // I assume you initialized your slider with 0

and inside your dragCompleted method.

```
onDragCompleted: (handlerIndex, lowerValue, upperValue) {
    _lowerValue = lowerValue;
    setState(() {});
  },
```

**Comment by PrashantGauravSingh** [comment]
@Ali-Azmoud  Issue is still persisting for me . Any other way to handle this
