### ISSUE TITLE
Exception thrown upon Navigation

### ISSUE THREAD

**Issue by Presheda** [Ali-Azmoud/flutter_xlider#77]
![Screenshot (40)](https://user-images.githubusercontent.com/26353504/86495859-e7236780-bd72-11ea-8a6a-748e94cc7cb7.png)

**Comment by Ali-Azmoud** [comment]
Hi. can you please provide a sample code so I can reproduce and test it?

**Comment by Presheda** [comment]
The error no longer occur. i don't know why but if it comes again i will re-open the issue
