### ISSUE TITLE
Very hard to drag slider to max value

### ISSUE THREAD

**Issue by dexcell** [Ali-Azmoud/flutter_xlider#8]
Somehow it's very hard to drag to max value. 
(tested on ios simulator and device, haven't tried on android).

Here is the vid in ios simulator (i'm clicking the mouse and drag it, however it cannot reach max value)
![1](https://user-images.githubusercontent.com/41800/55294415-2191ac80-542c-11e9-8771-713bece3cb14.gif)

````
FlutterSlider(
    jump: true,
    tooltip: FlutterSliderTooltip(
        disabled: true,
    ),
    trackBar: FlutterSliderTrackBar(
        activeTrackBarColor: Colors.blue[500],
    ),
    handler: FlutterSliderHandler(
        child: Container(
            width: 32,
            height: 32,
            decoration: new BoxDecoration(
                border: Border.all(color: Colors.blue, width: 3),
                color: Colors.white,
                shape: BoxShape.circle,
            ),
        ),
    ),
    values: [500000],
    min: 100000,
    max: 1000000,
    step: 100000,
    onDragging: (handlerIndex, lowerValue, upperValue) {
    },
)
````

**Comment by Ali-Azmoud** [comment]
Hi, I'm not sure but I think it's because of rounding numbers ( to make jump work). I try to figure that out. sorry for the bug.

**Comment by Ali-Azmoud** [comment]
Hi again, you can update and it should work fine ( working for me with no problem ). this bug made me to change the way handlers are moved, it's more accurate now. thanks for your bug reporting

**Comment by Ali-Azmoud** [comment]
Hi, new version is out, although your problem still exists in the newest version, but handler movement is far better than before. 

Your problem is because you drag the handler from the rightmost part of handler. to solve it,
**if your slider is full width or there is not enough room in both sides**, you should set `touchSize` equal or less than the padding of the container of your slider.

```dart
Container(
            padding: EdgeInsets.symmetric(horizontal: 50), // padding should be more than touchSize
            child: FlutterSlider(

               touchSize: 30

            ),
)
```

I hope this helps.

**Comment by dexcell** [comment]
Thank you i will try and report the result

**Comment by g-balas** [comment]
hey @Ali-Azmoud, got the same issue.
I tried adding some padding, but it does not fix the issue. It's a bit better but not usable for a production app.

**Comment by g-balas** [comment]
Here with padding, still missing the last sometimes, on version 2.3.1:

![glitch_xlider_2](https://user-images.githubusercontent.com/3330823/55568220-9a7c5700-56ff-11e9-83df-0ff21860f2d1.gif)

**Comment by Ali-Azmoud** [comment]
OK , I think I fixed the problem, testing it out to be sure. If everything goes well, I will upload it in the next couple of hours or less.

**Comment by Ali-Azmoud** [comment]
Hey, package is updated. I tried my best to test everything works fine, if you found any bug, please report it here. 👍

**Comment by Ali-Azmoud** [comment]
Hey. Could you @dexcell @g-balas please report the result of this issue.

**Comment by dexcell** [comment]
Hi @Ali-Azmoud 
Thank you very much for the update, it works really well now.
